import { useRef, useState } from "react";
import { Camera, FileText, ScanLine, ShieldAlert, Upload } from "lucide-react";
import PageHero from "../../components/PageHero/PageHero";
import { images } from "../../data/images";
import "./DailyEssentialsTools.css";
const apiBaseUrl = (import.meta.env.VITE_API_URL || "https://mauiza-backend.onrender.com").replace(/\/+$/, "");
const API = `${apiBaseUrl}/api/halal/analyze`;
export default function HalalScanner() { const [text, setText] = useState(""), [message, setMessage] = useState(""), [loading, setLoading] = useState(false), [results, setResults] = useState([]); const fileRef = useRef();
 const analyze = async () => { if (!text.trim()) return setMessage("Add ingredient text before analysing."); setLoading(true); setMessage(""); try { const response = await fetch(API, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ingredients: text }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "The ingredient database could not be reached."); setResults(data.results || []); if (!data.results?.length) setMessage("No matching ingredient records were returned."); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
 const readImage = async file => { if (!file) return; setMessage(""); setLoading(true); try { const image = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); const response = await fetch(`${apiBaseUrl}/api/halal/ocr`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ image }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "We couldn't read this image. Please try a clearer label."); setText(data.text || ""); if (!data.text) setMessage("No ingredient text was found. You can type it manually below."); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
 return <main className="page tool-page"><PageHero title="Smart Halal Ingredient Scanner" subtitle="Review ingredient labels carefully and connect to trusted halal data." image={images.namaz}/><section className="section tool-section"><div className="container scanner-layout"><div className="scanner-upload"><ScanLine /><h2>Scan an ingredient label</h2><p>Upload a clear photo or take one from your phone. You can always review the extracted text before analysis.</p><input ref={fileRef} hidden type="file" accept="image/*" capture="environment" onChange={e => readImage(e.target.files?.[0])}/><button className="tool-button" onClick={() => fileRef.current?.click()}><Upload />Upload or take photo</button></div><div className="scanner-editor"><label htmlFor="ingredients"><FileText /> Ingredient text</label><textarea id="ingredients" value={text} onChange={e => setText(e.target.value)} placeholder="e.g. sugar, emulsifier (E471), flavouring…" rows="9"/><button className="tool-button" onClick={analyze} disabled={loading}>{loading ? "Checking…" : "Analyse ingredients"}</button>{message && <p className="tool-alert"><ShieldAlert />{message}</p>}{results.length > 0 && <div className="ingredient-results">{results.map((item, index) => <article key={item.id || index}><strong>{item.name} {item.eNumber && `(${item.eNumber})`}</strong><span className={`status ${String(item.classification).toLowerCase().replace(/\s/g, "-")}`}>{item.classification}</span><p>{item.reason}</p><small>{item.source || "Source not provided"}</small></article>)}</div>}</div><p className="tool-disclaimer">The scanner provides informational guidance based on available ingredient data. Ingredient sources and manufacturing processes may vary. Verify uncertain ingredients and official halal certification when necessary.</p></div></section></main>; }
